# Site settings
title: Hi -Jimmy
description: "My personal site."
url: "https://jimmyjhickey.com"

author:
  name: "Jimmy Hickey"
  email: "jimmyjhickey@gmail.com"
  url: "https://jimmyjhickey.com/"

# Build settings
baseurl: "/" # Change this to your relative path (ex: /blog/), or leave just a /

markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false
